### ISSUE TITLE
wanted help

### ISSUE THREAD

**Issue by theunknownk** [OptimusChen/ImageFactory-Quest#1]
i just downloaded this and was wondering how do i download images on this?

**Comment by FrozenAlex** [comment]
Images go in /sdcard/ModData/com.beatgames.beatsaber/Mods/ImageFactory/Images/
You can't really download new images in the mod, you need to copy them to this folder.

This really needs to go into the readme

**Comment by OptimusChen** [comment]
Adding to readme and closing issue.
